server:
  port: 8081

logging:
  level:
#    root: DEBUG
#    tech.jhipster: ERROR
    org.hibernate: INFO
#    org.springframework.boot: ERROR
#    com.kakaoi.mpc: DEBUG
#    com.kakaoi.mpc.web.rest.HealthController: ERROR
#    okhttp3.internal.http2: ERROR

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: 1234
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      poolName: Hikari
#      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#    initialization-mode: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
